### ISSUE TITLE
Unable to consume messages produced by Java application with AVRO schema

### ISSUE THREAD

**Issue by tommy38hk** [mtth/avsc#453] opened 2024-02-25 20:19 UTC
I am trying to consume a Kafka message produced by a Java application with schema definition using avro.

const { Kafka } = require('kafkajs');
const axios = require('axios');
const avroRegistry = require('avro-schema-registry');
const avro = require('avsc');
const { Partitioners } = require('kafkajs');

...

  await consumer.subscribe({ topic, fromBeginning: true });

    async function handleMessage(message) {
      try {
        const messageAsString = JSON.stringify(message);
        const messageObject = JSON.parse(messageAsString);
        const avroMessage = messageObject.message.value;

        console.log('messageObject:', messageObject);
        console.log('avroMessage:', avroMessage);
        const buffer = Buffer.from(avroMessage.data);
        console.log('buffer:', buffer);
        
        // Use Avro to decode the buffer
        //let type = avro.Type.forSchema(yourAvroSchema);
        let decoded = type.fromBuffer(buffer);
      } catch (error) {
        if (error instanceof avro.AvroError) {
          // Handle specific Avro decoding errors
          console.error('Avro decoding error:', error.message);
        } else {
          console.error('Unexpected error decoding message:', error);
        }
      }
    }

    await consumer.connect();
    await consumer.run({
      eachMessage: handleMessage,
    });

I can only access the "avroMessage" variable but not able to decode the Buffer.

I got the following error

{"level":"ERROR","timestamp":"2024-02-25T20:04:57.433Z","logger":"kafkage":"[Runner] Error when calling eachMessage","topic":"my-toipc","partition":0,"offset":"98","stack":"TypeError: Rside of 'instanceof' is not an object\n    at Runner.handleMessage [asge]
Note that the same message can be consumed in Java. And Java is using org.apache.avro.generic.GenericData.Record when producing the message.

**Comment by mtth** [comment] 2024-03-04 00:26
This is typically caused by invalid data fed to `avsc` (encoding mismatch, data prefix, ...). It's hard to say more without data to reproduce it.

**Comment by tommy38hk** [comment] 2024-03-05 19:44
I created a sample schema and message that produced the same error.
`
{
  "fields": [
    {
      "name": "id",
      "type": [
        "null",
        "long"
      ]
    },
    {
      "name": "name",
      "type": [
        "null",
        {
          "avro.java.string": "String",
          "type": "string"
        }
      ]
    },
    {
      "name": "email",
      "type": [
        "null",
        {
          "avro.java.string": "String",
          "type": "string"
        }
      ]
    },
    {
      "name": "timestamp",
      "type": [
        "null",
        "long"
      ]
    },
    {
      "name": "items",
      "type": [
        "null",
        {
          "items": {
            "fields": [
              {
                "name": "name",
                "type": [
                  "null",
                  {
                    "avro.java.string": "String",
                    "type": "string"
                  }
                ]
              },
              {
                "name": "price",
                "type": [
                  "null",
                  "double"
                ]
              }
            ],
            "name": "Item",
            "type": "record"
          },
          "type": "array"
        }
      ]
    }
  ],
  "name": "User",
  "namespace": "org.example.test.testkafka",
  "type": "record"
}
`
{
  "id": 1,
  "name": "John Doe",
  "email": "john.doe@example.com",
  "timestamp": 1709667230821,
  "items": [
    {
      "name": "Product A",
      "price": 19.99
    }
  ]
}

**Comment by mtth** [comment] 2024-03-25 04:22
The producer code doesn't have enough information; we need to see what data `avsc` tries to decode. Can you share the value of `message` in your example?

**Comment by tommy38hk** [comment] 2024-03-25 11:41
I had already shared, I am reposting again here
```
{
  "id": 1,
  "name": "John Doe",
  "email": "john.doe@example.com",
  "timestamp": 1709667230821,
  "items": [
    {
      "name": "Product A",
      "price": 19.99
    }
  ]
}```

**Comment by mtth** [comment] 2024-03-27 02:54
That doesn't look like `message`, it doesn't have the right fields:

```js
async function handleMessage(message) { // We need this message
  try {
    const messageAsString = JSON.stringify(message);
    const messageObject = JSON.parse(messageAsString);
    const avroMessage = messageObject.message.value;
    const buffer = Buffer.from(avroMessage.data); // So we can see the buffer avsc sees
    let type = avro.Type.forSchema(yourAvroSchema);
    let decoded = type.fromBuffer(buffer);
// ...
```

**Comment by tommy38hk** [comment] 2024-03-27 12:23
I added some console.log in between as follows:-
```
		const messageAsString = JSON.stringify(message);
		const messageObject = JSON.parse(messageAsString);

		console.log('messageObject:', messageObject);
		const bufferData = Buffer.from(messageObject.message.value.data);
		
		const hexString = bufferData.toString('hex');
		const formattedString = hexString.match(/../g).join(' ');
		const decodedString = formattedString.toString("utf-8");
		const buffer2 = Buffer.from(decodedString)
		const decodedString2 = buffer2.toString("utf-8");
		console.log(decodedString2); 
		let decoded = type.fromBuffer(bufferData);

```
And the output is 
```
node consume-schema-topic.js
messageObject: {
  topic: 'example',
  partition: 0,
  message: {
    magicByte: 2,
    attributes: 0,
    timestamp: '1711541805856',
    offset: '0',
    key: null,
    value: { type: 'Buffer', data: [Array] },
    headers: {},
    isControlRecord: false,
    batchContext: {
      firstOffset: '0',
      firstTimestamp: '1711541805856',
      partitionLeaderEpoch: 0,
      inTransaction: false,
      isControlBatch: false,
      lastOffsetDelta: 0,
      producerId: '95946902',
      producerEpoch: 0,
      firstSequence: 0,
      maxTimestamp: '1711541805856',
      timestampType: 0,
      magicByte: 2
    }
  }
}
00 00 01 87 1b 02 02 02 10 4a 6f 68 6e 20 44 6f 65 02 28 6a 6f 68 6e 2e 64 6f 65 40 65 78 61 6d 70 6c 65 2e 63 6f 6d 02 d6 fa ba fd cf 63 02 02 02 12 50 72 6f 64 75 63 74 20 41 02 3d 0a d7 a3 70 fd 33 40 00
{"level":"ERROR","timestamp":"2024-03-27T12:19:23.782Z","logger":"kafkajs","message":"[Runner] Error when calling eachMessage","topic":"example","partition":0,"offset":"0","stack":"TypeError: Right-hand side of 'instanceof' is not an object\n    at Runner.handleMessage [as eachMessage] (C:\\Users\\myuserid\\testkafka\\consume-schema-topic.js:166:13)\n    at Runner.processEachMessage (C:\\Users\\myuserid\\testkafka\\node_modules\\kafkajs\\src\\consumer\\runner.js:231:20)\nat onBatch (C:\\Users\\myuserid\\testkafka\\node_modules\\kafkajs\\src\\consumer\\runner.js:447:20)\n    at Runner.handleBatch (C:\\Users\\myuserid\\testkafka\\node_modules\\kafkajs\\src\\consumer\\runner.js:461:11)\n    at handler (C:\\Users\\myuserid\\testkafka\\node_modules\\kafkajs\\src\\consumer\\runner.js:58:30)\n    at C:\\Users\\myuserid\\testkafka\\node_modules\\kafkajs\\src\\consumer\\worker.js:29:15\n    at Object.run (C:\\Users\\myuserid\\testkafka\\node_modules\\kafkajs\\src\\utils\\sharedPromiseTo.js:14:17)\n    at C:\\Users\\myuserid\\testkafka\\node_modules\\kafkajs\\src\\consumer\\workerQueue.js:27:38\n    at Array.forEach (<anonymous>)\n    at Object.push (C:\\Users\\myuserid\\testkafka\\node_modules\\kafkajs\\src\\consumer\\workerQueue.js:27:13)","error":{}}{"level":"ERROR","timestamp":"2024-03-27T12:19:28.065Z","logger":"kafkajs","message":"[Consumer] Crash: KafkaJSNonRetriableError: Right-hand side of 'instanceof' is not an object","groupId":"microservice1-consumer-group","stack":"KafkaJSNonRetriableError: Right-hand side of 'instanceof' is not an object\n    at C:\\Users\\myuserid\\testkafka\\node_modules\\kafkajs\\src\\retry\\index.js:55:18\nat process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}{"level":"INFO","timestamp":"2024-03-27T12:19:28.135Z","logger":"kafkajs","message":"[Consumer] Stopped","groupId":"microservice1-consumer-group"}
C:\Users\myuserid\testkafka>
```

**Comment by tommy38hk** [comment] 2024-03-28 11:56
Thanks @mtth. This is working as per suggestion. Just that I am not sure if it is always starting from 5.

**Comment by mtth** [comment] 2024-03-30 15:27
I'm afraid this out of scope of `avsc`. You'll need to dig into the upstream system setup to figure out the prefix' properties.

**Closed by mtth** 2024-03-30 15:27 UTC
Labels: question
